config/routes.rb
Rails.application.routes.draw do

  resources :user_votes

  resources :robots do
    get 'results', :on => :collection
  end

  devise_for :users do
    member do
      get 'users#dashboard'
    end
  end

  devise_scope :user do
    authenticated :user do
      root 'users#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/user_vote.rb
class UserVote < ActiveRecord::Base
  belongs_to :user
  has_one    :robot
end

app/controllers/user_votes_controller.rb
class UserVotesController < ApplicationController
  before_action :set_user_vote, only: [:show, :edit, :update, :destroy]

  # GET /user_votes
  # GET /user_votes.json
  def index
    @user_votes = UserVote.all
  end

  # GET /user_votes/1
  # GET /user_votes/1.json
  def show
  end

  # GET /user_votes/new
  def new
    @user_vote = UserVote.new
  end

  # GET /user_votes/1/edit
  def edit
  end

  # POST /user_votes
  # POST /user_votes.json
  def create
    @user_vote = UserVote.new(user_id: params[:user_id], robot_id: params[:robot_id])

    respond_to do |format|
      if @user_vote.save
        format.html { redirect_to :robots, notice: 'You casted a vote!' }
        format.json { render :robots, status: :created, location: @user_vote }
      else
        format.html { render :robots }
        format.json { render json: @user_vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_votes/1
  # PATCH/PUT /user_votes/1.json
  def update
    respond_to do |format|
      if @user_vote.update(user_vote_params)
        format.html { redirect_to @user_vote, notice: 'User vote was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_vote }
      else
        format.html { render :edit }
        format.json { render json: @user_vote.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_votes/1
  # DELETE /user_votes/1.json
  def destroy
    @user_vote.destroy
    respond_to do |format|
      format.html { redirect_to user_votes_url, notice: 'User vote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_vote
      @user_vote = UserVote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_vote_params
      params.require(:user_vote).permit(:user_id, :robot_id)
    end
end

app/helpers/user_votes_helper.rb
module UserVotesHelper
end

app/views/user_votes/_form.html.erb
<%= form_for(@user_vote) do |f| %>
  <% if @user_vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_vote.errors.count, "error") %> prohibited this user_vote from being saved:</h2>

      <ul>
      <% @user_vote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :robot_id %><br>
    <%= f.number_field :robot_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/user_votes/edit.html.erb
<h1>Editing User Vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @user_vote %> |
<%= link_to 'Back', user_votes_path %>

app/views/user_votes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing User Votes</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Robot</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @user_votes.each do |user_vote| %>
      <tr>
        <td><%= user_vote.user_id %></td>
        <td><%= user_vote.robot_id %></td>
        <td><%= link_to 'Show', user_vote %></td>
        <td><%= link_to 'Edit', edit_user_vote_path(user_vote) %></td>
        <td><%= link_to 'Destroy', user_vote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User vote', new_user_vote_path %>

app/views/user_votes/new.html.erb
<h1>New User Vote</h1>

<%= render 'form' %>

<%= link_to 'Back', user_votes_path %>

app/views/user_votes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @user_vote.user_id %>
</p>

<p>
  <strong>Robot:</strong>
  <%= @user_vote.robot_id %>
</p>

<%= link_to 'Edit', edit_user_vote_path(@user_vote) %> |
<%= link_to 'Back', user_votes_path %>