config/routes.rb
Rails.application.routes.draw do

  resources :user_votes

  resources :robots do
    get 'results', :on => :collection
  end

  devise_for :users do
    member do
      get 'users#dashboard'
    end
  end

  devise_scope :user do
    authenticated :user do
      root 'users#dashboard', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

end

app/models/robot.rb
class Robot < ActiveRecord::Base
  belongs_to :user
  has_many   :user_votes
  has_attached_file :image,
    :path => ":rails_root/public/system/:attachment/:id/:style/:filename",
    :url => "/system/:attachment/:id/:style/:filename",
    :styles => { :medium => "300x300>", :small => "200x200>" },
    :default_url => "path to default image"
  do_not_validate_attachment_file_type :image

end

app/controllers/robots_controller.rb
class RobotsController < ApplicationController
  before_action :set_robot, only: [:show, :edit, :update, :destroy]
  before_filter :is_user_admin, only: [:create, :new]

  # GET /robots
  # GET /robots.json
  def index
    @robots = Robot.all
    @owned_robots = current_user.robots
    @your_voted_robots = Robot.all.select{|robot| robot.user_votes.any?{|vote| vote.user_id == current_user.id }}
  end

  def results
    @robots = Robot.all
  end

  # GET /robots/1
  # GET /robots/1.json
  def show
  end

  # GET /robots/new
  def new
    @owned_robots = current_user.robots
    @robots = Robot.all
    @robot = Robot.new
  end

  # GET /robots/1/edit
  def edit
  end

  # POST /robots
  # POST /robots.json
  def create
    @robot = Robot.new(robot_params)

    respond_to do |format|
      if @robot.save
        format.html { redirect_to new_robot_path, notice: 'Robot was successfully created.' }
        format.json { render :new, status: :created, location: @robot }
      else
        format.html { render :new }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /robots/1
  # PATCH/PUT /robots/1.json
  def update
    respond_to do |format|
      if @robot.update(robot_params)
        format.html { redirect_to new_robot_path, notice: 'Robot was successfully updated.' }
        format.json { render :show, status: :ok, location: @robot }
      else
        format.html { render :new }
        format.json { render json: @robot.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /robots/1
  # DELETE /robots/1.json
  def destroy
    @robot.destroy
    respond_to do |format|
      format.html { redirect_to new_robot_path, notice: 'Robot was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_robot
      @robot = Robot.find(params[:id])
    end

    def is_user_admin
      if current_user.admin?

      else
        respond_to do |format|
          format.html { redirect_to robots_path, notice: 'You must be an admin to create a new robot. How about voteing for one instead!' }
          format.json { head :no_content }
        end
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def robot_params
      params.require(:robot).permit(:image, :name, :user_id, :description)
    end
end

app/helpers/robots_helper.rb
module RobotsHelper
end

app/views/robots/_form.html.erb
<%= form_for @robot do |f| %>
  <% if @robot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@robot.errors.count, "error") %> prohibited this robot from being saved:</h2>

      <ul>
      <% @robot.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name, style: 'padding-top: 65px;' %><br>
    <% if params[:action] == 'edit' %>
      <%= f.text_field :name, style: 'width: 50%' %>
    <% else %>
      <%= f.text_field :name, style: 'width: 90%' %>
    <% end %>
  </div>
  <div class="field">
    <%= f.label :image %><br>
    <% if params[:action] == 'edit' %>
      <%= f.file_field :image, class: 'form-control', style: 'width: 50%; margin-left: 25%;' %>
    <% else %>
      <%= f.file_field :image, class: 'form-control', style: 'width: 88%; margin-left: 15px;' %>
    <% end %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, value: current_user.id %>
  </div>
  <div class="actions" style="padding-top: 15px; padding-bottom: 40px;">
    <% if params[:action] == 'edit' %>
      <%= f.submit 'Update Robot', class: 'btn btn-info' %>
    <% else %>
      <%= f.submit 'Add Robot', class: 'btn btn-info' %>
    <% end %>
  </div>
<% end %>

app/views/robots/edit.html.erb
<div class="container">
  <h3 style="color: #7C7C7D; padding-bottom: 25px; padding-top: 25px; text-align: center;">Editing Robot</h3>
  <div class="row col-lg-12" style="text-align: center;">
    <p id="notice"><%= notice %></p>

    <div class="col-lg-12" style="color: #7C7C7D; background-color: white; border: 30px solid #F8F9FA !important; font-size: 25px;"><%= render 'form' %></div>

  </div>
</div>

app/views/robots/index.html.erb
<div class="container">
  <h3 style="color: #7C7C7D; padding-bottom: 25px; padding-top: 25px; text-align: center;">Vote Here!
    <p id="notice"><%= notice %></p>
  </h3>
  <div class="row col-lg-12" style="text-align: center;">
    <table>
      <tbody>
        <% @robots.each do |robot| %>
          <div class="col-lg-4" style="background-color: white; border: 30px solid #F8F9FA !important;">
            <%= link_to image_tag(robot.image.url(:medium)), robot, class: '' %>
            <p><%= robot.name %></p>
            <% if @your_voted_robots.any?{|voted_bot| voted_bot == robot } %>
              <%= button_tag 'Voted', class: 'btn btn-warning', style: 'margin-bottom: 15px;', disabled: true %>
            <% else %>
              <%= link_to 'Vote', { controller: :user_votes, action: :create, :user_id => current_user.id, :robot_id => robot.id },  method:"post", class: 'btn btn-success', style: 'margin-bottom: 15px;' %>
            <% end %>
          </div>
        <% end %>
      </tbody>
    </table>
    <br>
  </div>
</div>

app/views/robots/new.html.erb
<div class="container">
  <h3 style="color: #7C7C7D; padding-bottom: 25px; padding-top: 25px; text-align: center;">Admin</h3>
  <div class="row col-lg-12" style="text-align: center;">
    <p id="notice"><%= notice %></p>
    <table>
      <tbody>
        <% @robots.each do |robot| %>
          <div class="col-lg-4" style="background-color: white; border: 30px solid #F8F9FA !important;">
            <%= link_to image_tag(robot.image.url(:medium)), robot, class: 'col-lg-1' %>
            <p style="font-size: 25px; color: #7C7C7D;"><%= robot.name%></p>
            <%= link_to 'Edit', edit_robot_path(robot), class: 'btn btn-info', style: 'margin-bottom: 10px;' %></td>
            <%= link_to 'Destroy', robot, method: :delete, data: { confirm: 'Are you sure?'}, class: 'btn btn-danger', style: 'margin-bottom: 10px;' %>
          </div>
        <% end %>
        <div class="col-lg-4" style="color: #7C7C7D; background-color: white; border: 30px solid #F8F9FA !important; padding-top: 25px; font-size: 25px;"><b>Add Robot</b><%= render 'form' %></div>
      </tbody>
    </table>
    <br>
  </div>
</div>

app/views/robots/results.html.erb
<div class="container">
  <h3 style="color: #7C7C7D; padding-bottom: 25px; padding-top: 25px; text-align: center;">Hello <%= current_user.first_name.to_s %>, check out how your bots are ranking!
      <p id="notice"><%= notice %></p>
  </h3>
  <div class="row col-lg-12">
    <table>
      <tbody>
        <% @robots.each do |robot| %>
          <div class="col-lg-12" style="background-color: white; border: 30px solid #F8F9FA !important;">
            <%= link_to image_tag(robot.image.url(:thumb)), robot, class: '' %>
            <p><%= robot.name %></p>
            Votes:
            <div class="progress">
              <div class="progress-bar progress-bar-info" role="progressbar" aria-valuenow="<%= robot.user_votes.count %>"
              aria-valuemin="0" aria-valuemax="100" style="width:<%=robot.user_votes.count%>%">
                <%= robot.user_votes.count %> Votes
              </div>
            </div>
          </div>
        <% end %>
      </tbody>
    </table>
    <br>
  </div>
</div>

app/views/robots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @robot.name %>
</p>

<p>
  <strong>Owner:</strong>
  <%= @robot.user.first_name + " " + @robot.user.last_name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @robot.description %>
</p>

<%= link_to 'Edit', edit_robot_path(@robot) %> |
<%= link_to 'Back', robots_path %>